### ISSUE TITLE
Implement `Grid.from_points()`

### ISSUE THREAD

**Issue by philipc2** [UXARRAY/uxarray#1020] opened 2024-10-15 14:43 UTC
### Proposed new feature or change:

The `Grid.from_points()` class method should be used when constructing a grid from coordinates.

**Comment by aaronzedwick** [comment] 2024-10-15 14:58
@philipc2 This seems to be a duplicate of #349

**Comment by aaronzedwick** [comment] 2024-10-15 14:59
Oh, you're just using it for the sub-issues, never mind.

**Closed** 2024-11-04 16:21 UTC
Labels: new feature
