### ISSUE TITLE
Testing, a baggage for development

### ISSUE THREAD

**Issue by rajeeja** [UXARRAY/uxarray#581] opened 2023-11-12 16:35 UTC
### Proposed new feature or change:

As our test suite has grown to over 100 tests, we need to consider our approach to testing in order to maintain our development agility. While comprehensive testing is essential, it's crucial to balance thoroughness with efficiency. I propose that we temporarily reduce the scope of our test coverage while maintaining our current level of documentation and examples. This will allow us to focus on adding new functionality without sacrificing code quality. We can always revisit and expand our test coverage as needed. Additionally, I encourage us to continuously improve our documentation, as demonstrated in one of our current pull request.

**Comment by philipc2** [comment] 2023-11-12 18:29
We should definitely consider a complete rewrite of our testing implementations in the near future, using Pytest instead of Unittest also.

**Comment by philipc2** [comment] 2024-09-16 23:04
Closing this as it is a duplicate of #52, #415, #212

**Closed by philipc2** 2024-09-16 23:04 UTC
Labels: new feature
