### ISSUE TITLE
Add build_node_face_connectivity

### ISSUE THREAD

**Issue by anissa111** [UXARRAY/uxarray#80] opened 2022-07-21 22:56 UTC
Add `build_node_face_connectivity` described in the [uxarray_api](https://github.com/UXARRAY/uxarray/blob/main/docs/user_api/uxarray_api.md) document

**Comment by philipc2** [comment] 2023-07-14 18:07
Duplicate of #130

**Closed by philipc2** 2023-07-14 18:07 UTC
Labels: enhancement
